import {
  BarChart3,
  Bell,
  Boxes,
  Building2,
  CalendarClock,
  CalendarDays,
  CircleUser,
  ClipboardList,
  Coins,
  CreditCard,
  FileSignature,
  Globe,
  FileText,
  Gift,
  HelpCircle,
  Home,
  KeyRound,
  LayoutGrid,
  LineChart,
  List,
  Mail,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Newspaper,
  Package,
  PackageX,
  Percent,
  Phone,
  PieChart,
  LifeBuoy,
  Plug,
  PlusCircle,
  Receipt,
  RotateCcw,
  Scale,
  Send,
  Settings,
  Smartphone,
  Star,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Store,
  Tablet,
  TabletSmartphone,
  Tag,
  TrendingDown,
  Truck,
  UserPlus,
  Users,
  UsersRound,
  Wrench,
} from 'lucide-react';

/**
 * `ADMIN_NAV` and `ADMIN_ROUTES` name icons as strings so they stay plain data
 * modules the server can read. This is the one place those names become
 * components - import the map, not lucide, from admin shell code.
 */
export const ADMIN_ICONS = {
  BarChart3,
  Bell,
  Boxes,
  Building2,
  CalendarClock,
  CalendarDays,
  CircleUser,
  ClipboardList,
  Coins,
  CreditCard,
  FileSignature,
  Globe,
  FileText,
  Gift,
  HelpCircle,
  Home,
  KeyRound,
  LayoutGrid,
  LineChart,
  List,
  Mail,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Newspaper,
  Package,
  PackageX,
  Percent,
  Phone,
  PieChart,
  LifeBuoy,
  Plug,
  PlusCircle,
  Receipt,
  RotateCcw,
  Scale,
  Send,
  Settings,
  Smartphone,
  Star,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Store,
  Tablet,
  TabletSmartphone,
  Tag,
  TrendingDown,
  Truck,
  UserPlus,
  Users,
  UsersRound,
  Wrench,
};

/** Named icon or nothing - a missing key must not crash a nav row. */
export function adminIcon(name) {
  return ADMIN_ICONS[name] ?? null;
}

export default ADMIN_ICONS;
