import { useState } from 'react';
import { Link, useSearchParams } from 'react-router';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import useAdminForm from '@/hooks/useAdminForm';
import useCreateParam from '@/hooks/useCreateParam';
import {
  AlertCircle,
  ClipboardList,
  Clock,
  Pencil,
  Percent,
  Plus,
  Receipt,
  Tags,
  Trash2,
  Wallet,
} from 'lucide-react';
import { money, date, count as formatCount } from '@/lib/format';
import Panel, { PanelEmpty } from '@/components/ui/Panel';
import Modal from '@/components/ui/Modal';
import ConfirmDialog from '@/components/ui/ConfirmDialog';
import Input from '@/components/ui/Input';
import Textarea from '@/components/ui/Textarea';
import SelectField from '@/components/ui/SelectField';
import Checkbox from '@/components/ui/Checkbox';
import Button from '@/components/ui/Button';
import Badge from '@/components/ui/Badge';
import PageHeader from '@/components/admin/PageHeader';
import KpiRow from '@/components/admin/KpiRow';
import FilterStrip from '@/components/admin/FilterStrip';
import DataTable, { CountLine } from '@/components/admin/DataTable';
import Pagination from '@/components/ui/Pagination';
import useTablePage from '@/hooks/useTablePage';
import { ADMIN_ROUTES } from '@/lib/adminRoutes';
import { adminIcon } from '@/components/admin/shell/adminIcons';
import downloadExport from '@/lib/exportDownload';
import { pressable } from '@/lib/motion';
import cn from '@/lib/cn';
import SelectMenu from '@/components/ui/SelectMenu';
import {
  useAdminExpenses,
  useAdminExpenseCategories,
  useAdminMutations,
} from '@/hooks/useAdmin';

/**
 * Expenses - money out, categorised and taxed, feeding the P&L (§6.9).
 *
 * Rows generated by a purchase-order payment are **labelled and link back**, so
 * a staff member can tell what they entered from what the system entered for them.
 * Those rows are not editable here; the purchase order owns them, and letting
 * both surfaces write would give the P&L two numbers to choose between.
 */
const ADMIN_PAGE = { ...ADMIN_ROUTES['/admin/expenses'], icon: adminIcon('Receipt') };

const PILLS = [
  { value: 'all', label: 'All' },
  { value: 'paid', label: 'Paid' },
  { value: 'pending', label: 'Pending' },
];

const METHODS = [
  { value: 'Credit card', label: 'Credit card' },
  { value: 'e-Transfer', label: 'e-Transfer' },
  { value: 'Cheque', label: 'Cheque' },
  { value: 'Pre-authorised debit', label: 'Pre-authorised debit' },
  { value: 'Direct deposit', label: 'Direct deposit' },
  { value: 'Cash', label: 'Cash' },
  { value: 'Other', label: 'Other' },
];

/** `YYYY-MM-DD` in local time - `toISOString()` would shift the day westward. */
function todayIso() {
  const now = new Date();
  return new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 10);
}

function isoDay(value) {
  if (!value) return todayIso();
  const parsed = new Date(value);
  return new Date(parsed.getTime() - parsed.getTimezoneOffset() * 60_000)
    .toISOString()
    .slice(0, 10);
}

/**
 * What the FORM holds.
 *
 * Money is typed in dollars here and stored in cents, so `expenseSchema`'s
 * `amount` is this form's `amountDollars` and the conversion happens on
 * submit. A blank amount is caught here rather than arriving as `NaN` cents.
 */
const expenseFormSchema = z.object({
  date: z.string().trim().min(1, 'Pick a date.'),
  description: z.string().trim().min(1, 'Say what this was for.').max(200),
  category: z.string().trim().min(1, 'Choose a category.'),
  payee: z.string().trim().max(120).optional().or(z.literal('')),
  method: z.string().trim(),
  status: z.string().trim(),
  amountDollars: z.coerce.number({ invalid_type_error: 'Enter an amount.' }).min(0.01, 'Enter an amount.'),
  taxDollars: z.coerce.number({ invalid_type_error: 'Enter a number, or 0.' }).min(0),
  taxIncluded: z.boolean(),
  reference: z.string().trim().max(120).optional().or(z.literal('')),
  notes: z.string().trim().max(2000).optional().or(z.literal('')),
});

function ExpenseForm({ expense, categories, onSubmit, onCancel, isPending, error }) {
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useAdminForm({
    resolver: zodResolver(expenseFormSchema),
    defaultValues: {
      date: isoDay(expense?.date),
      description: expense?.description ?? '',
      category: expense?.category?.id ?? categories[0]?.id ?? '',
      payee: expense?.payee ?? '',
      method: expense?.method ?? 'Credit card',
      status: expense?.status ?? 'paid',
      amountDollars: expense ? (expense.amount / 100).toFixed(2) : '',
      taxDollars: expense ? (expense.tax / 100).toFixed(2) : '0.00',
      taxIncluded: expense?.taxIncluded ?? true,
      reference: expense?.reference ?? '',
      notes: expense?.notes ?? '',
    },
  });

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      {error && (
        <p className="flex items-start gap-2 rounded-md bg-danger-50 px-3 py-2.5 text-sm text-danger">
          <AlertCircle className="mt-0.5 size-4 shrink-0" strokeWidth={2} aria-hidden="true" />
          {error}
        </p>
      )}

      <div className="grid gap-3 sm:grid-cols-[140px_1fr]">
        <Input label="Date" type="date" required error={errors.date?.message} {...register('date')} />
        <Input
          label="Description"
          placeholder="Bench supplies"
          required
          error={errors.description?.message}
          {...register('description')}
        />
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <SelectField
          control={control}
          name="category"
          label="Category"
          options={categories.map((category) => ({ value: category.id, label: category.name }))}
        />
        <Input label="Payee" placeholder="Who it was paid to" error={errors.payee?.message} {...register('payee')} />
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <SelectField control={control} name="method" label="Method" options={METHODS} />
        <SelectField
          control={control}
          name="status"
          label="Status"
          options={[
            { value: 'paid', label: 'Paid' },
            { value: 'pending', label: 'Pending' },
          ]}
        />
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <Input
          label="Amount"
          inputMode="decimal"
          suffix="CAD"
          placeholder="0.00"
          required
          error={errors.amountDollars?.message}
          {...register('amountDollars')}
        />
        <Input
          label="Tax"
          inputMode="decimal"
          suffix="CAD"
          placeholder="0.00"
          error={errors.taxDollars?.message}
          {...register('taxDollars')}
        />
      </div>

      <Checkbox label="Tax is included in the amount" {...register('taxIncluded')} />

      <Input label="Reference" placeholder="Receipt or invoice number" {...register('reference')} />
      <Textarea label="Notes" rows={2} {...register('notes')} />

      <div className="flex justify-end gap-2">
        <Button type="button" variant="ghost" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit" loading={isPending}>
          {expense ? 'Save expense' : 'Add expense'}
        </Button>
      </div>
    </form>
  );
}

export function AdminExpensesPage() {
  const [query, setQuery] = useState('');
  const [editing, setEditing] = useState(null);
  // Opened directly by `+ Create` (§7.2), which arrives with `?new=1`.
  const [creating, setCreating] = useCreateParam();
  const [deleting, setDeleting] = useState(null);
  const [searchParams, setSearchParams] = useSearchParams();

  const status = searchParams.get('status') ?? 'all';
  const category = searchParams.get('category') ?? '';
  const from = searchParams.get('from') ?? '';
  const to = searchParams.get('to') ?? '';

  const { data, isLoading } = useAdminExpenses({
    status,
    category: category || undefined,
    from: from || undefined,
    to: to || undefined,
    q: query || undefined,
  });
  const { data: categoryData } = useAdminExpenseCategories();
  const { createExpense, updateExpense, deleteExpense } = useAdminMutations();

  const expenses = data?.expenses ?? [];

  // The KPI tiles are summed from the whole filtered set; the table gets a
  // page of it. See `useTablePage` for why paging is client-side.
  const { pageRows: pageExpenses, page, totalPages, from: rowFrom, setPage } = useTablePage(expenses);
  const counts = data?.counts ?? {};
  const totals = data?.totals ?? {};
  const categories = (categoryData?.categories ?? []).filter((row) => row.isActive);

  function setParam(key, value) {
    const params = new URLSearchParams(searchParams);
    if (!value || value === 'all') params.delete(key);
    else params.set(key, value);
    setSearchParams(params, { replace: true });
  }

  const activeFilterCount = [category, from, to].filter(Boolean).length;

  function toPayload(values) {
    return {
      date: values.date,
      description: values.description,
      category: values.category,
      payee: values.payee || undefined,
      method: values.method || undefined,
      status: values.status,
      amount: Math.round(Number(values.amountDollars || 0) * 100),
      tax: Math.round(Number(values.taxDollars || 0) * 100),
      taxIncluded: Boolean(values.taxIncluded),
      reference: values.reference || undefined,
      notes: values.notes || undefined,
    };
  }

  const columns = [
    {
      key: 'date',
      header: 'Date',
      priority: 1,
      render: (expense) => (
        <span className="whitespace-nowrap text-sm text-ink-500">{date(expense.date)}</span>
      ),
    },
    {
      key: 'description',
      header: 'Description',
      priority: 1,
      className: 'max-w-[240px]',
      render: (expense) => (
        <>
          <span className="block truncate text-sm text-ink-900">{expense.description}</span>
          {/* A PO-generated row says so and links back - the staff member can tell
              what they entered from what the system entered for them. */}
          {expense.purchaseOrder && (
            <Link
              to={`/admin/purchase-orders/${expense.purchaseOrder.id}`}
              onClick={(event) => event.stopPropagation()}
              className="mt-0.5 inline-flex items-center gap-1 text-2xs text-ink-400 hover:text-brand"
            >
              <ClipboardList className="size-3 shrink-0" strokeWidth={2.5} aria-hidden="true" />
              {expense.purchaseOrder.poNumber ?? 'Purchase order'}
            </Link>
          )}
        </>
      ),
    },
    {
      key: 'category',
      header: 'Category',
      priority: 2,
      sortValue: (expense) => expense.category.name,
      render: (expense) => (
        <Badge tone="neutral" size="sm">
          {expense.category.name}
        </Badge>
      ),
    },
    {
      key: 'payee',
      header: 'Payee',
      priority: 3,
      className: 'max-w-[160px] truncate',
      render: (expense) => expense.payee ?? <span className="text-xs text-ink-300">-</span>,
    },
    {
      key: 'method',
      header: 'Method',
      priority: 3,
      render: (expense) => (
        <span className="text-sm text-ink-500">
          {expense.method ?? <span className="text-ink-300">-</span>}
        </span>
      ),
    },
    {
      key: 'status',
      header: 'Status',
      priority: 2,
      render: (expense) => (
        <Badge tone={expense.status === 'paid' ? 'ok' : 'warn'} size="sm">
          {expense.status}
        </Badge>
      ),
    },
    {
      key: 'amount',
      header: 'Amount',
      priority: 1,
      align: 'right',
      className: 'tnum',
      render: (expense) => (
        <>
          <span className="text-sm font-medium text-ink-900">{money(expense.amount)}</span>
          {expense.tax > 0 && (
            <span className="block text-2xs text-ink-400">{money(expense.tax)} tax</span>
          )}
        </>
      ),
    },
  ];

  const rowMenu = [
    {
      key: 'edit',
      label: 'Edit expense',
      icon: Pencil,
      // A PO-generated row is owned by its purchase order. The server refuses
      // the write regardless; this only saves the staff member the round trip.
      disabled: (expense) => Boolean(expense.purchaseOrder),
      onSelect: setEditing,
    },
    {
      key: 'delete',
      label: 'Delete expense',
      icon: Trash2,
      tone: 'danger',
      disabled: (expense) => Boolean(expense.purchaseOrder),
      onSelect: setDeleting,
    },
  ];

  return (
    <>
      <PageHeader
        icon={ADMIN_PAGE.icon}
        title={ADMIN_PAGE.title}
        description={ADMIN_PAGE.description}
        action={
          <>
            <Link
              to="/admin/settings/expense-categories"
              className={cn(pressable, 'inline-flex h-11 select-none items-center justify-center gap-2 rounded-md border border-line-strong bg-surface px-5 font-display text-md font-semibold text-ink-700 hover:border-ink-300 hover:bg-surface-2')}
            >
              <Tags className="size-4 shrink-0" strokeWidth={2} aria-hidden="true" />
              Categories
            </Link>
            <Button onClick={() => setCreating(true)} icon={Plus} disabled={!categories.length}>
              Add expense
            </Button>
          </>
        }
      />

      <KpiRow
        tiles={[
          {
            key: 'total',
            label: 'Total',
            value: money(totals.total ?? 0),
            // The KPI row describes the filtered set, because that is what is
            // on screen - a total ignoring the filters would contradict the
            // rows beneath it.
            hint: 'Across the rows shown',
            tone: 'warn',
            icon: Wallet,
          },
          {
            key: 'entries',
            label: 'Entries',
            value: formatCount(totals.entries ?? 0),
            hint: `${formatCount(counts.all ?? 0)} in total`,
            tone: 'neutral',
            icon: Receipt,
          },
          {
            key: 'pending',
            label: 'Pending',
            value: money(totals.pending ?? 0),
            hint: `${formatCount(counts.pending ?? 0)} not yet paid`,
            tone: (totals.pending ?? 0) > 0 ? 'danger' : 'ok',
            icon: Clock,
          },
          {
            key: 'tax',
            label: 'Tax included',
            value: money(totals.tax ?? 0),
            hint: 'GST/HST across the rows shown',
            tone: 'info',
            icon: Percent,
          },
        ]}
      />

      <Panel flush>
        <FilterStrip
          search={query}
          onSearchChange={setQuery}
          searchPlaceholder="Description, payee or reference…"
          pills={PILLS.map((pill) => ({ ...pill, count: counts[pill.value] }))}
          activePill={status}
          onPillChange={(next) => setParam('status', next)}
          activeFilterCount={activeFilterCount}
          onClearFilters={() => {
            const params = new URLSearchParams(searchParams);
            params.delete('category');
            params.delete('from');
            params.delete('to');
            setSearchParams(params, { replace: true });
          }}
          filters={
            <div className="space-y-3">
              <div>
                <p className="eyebrow mb-1.5 text-ink-400">Category</p>
                <SelectMenu
                  srLabel="Filter by category"
                  value={category}
                  onChange={(next) => setParam('category', next)}
                  options={[
                    { value: '', label: 'All categories' },
                    ...(categoryData?.categories ?? []).map((row) => ({
                      value: row.id,
                      label: row.name,
                    })),
                  ]}
                  containerClassName="w-full"
                />
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div>
                  <p className="eyebrow mb-1.5 text-ink-400">From</p>
                  <input
                    type="date"
                    value={from}
                    onChange={(event) => setParam('from', event.target.value)}
                    className="h-9 w-full rounded-md border border-line bg-surface px-2.5 text-sm text-ink-700"
                  />
                </div>
                <div>
                  <p className="eyebrow mb-1.5 text-ink-400">To</p>
                  <input
                    type="date"
                    value={to}
                    onChange={(event) => setParam('to', event.target.value)}
                    className="h-9 w-full rounded-md border border-line bg-surface px-2.5 text-sm text-ink-700"
                  />
                </div>
              </div>
            </div>
          }
          // The same object the list query uses, so the file and the screen
          // cannot disagree about what "current filters" means (§7.4).
          onExport={(format) =>
            downloadExport('expenses', format, {
              status,
              category: category || undefined,
              from: from || undefined,
              to: to || undefined,
              q: query || undefined,
            })
          }
        />

        <div className="border-b border-line px-3 py-2 sm:px-4">
          <CountLine
            total={expenses.length}
            shown={pageExpenses.length}
            from={rowFrom}
            noun={expenses.length === 1 ? 'expense' : 'expenses'}
          />
        </div>

        <DataTable
          columns={columns}
          rows={pageExpenses}
          rowKey={(expense) => expense.id}
          rowMenu={rowMenu}
          loading={isLoading}
          defaultSort={{ key: 'date', direction: 'desc' }}
          empty={
            <PanelEmpty
              icon={Receipt}
              title="No expenses match"
              body={
                categories.length
                  ? 'Try a different filter, or record what you spent.'
                  : 'Add an expense category first - every expense is filed under one.'
              }
            />
          }
        />

        <Pagination
          page={page}
          pages={totalPages}
          onChange={setPage}
          hideWhenSingle
          className="border-t border-line px-3 py-3 sm:px-4"
        />

      </Panel>

      <Modal
        open={creating}
        onClose={() => setCreating(false)}
        title="Add an expense"
        size="lg"
        align="top"
      >
        {creating && (
          <ExpenseForm
            categories={categories}
            isPending={createExpense.isPending}
            error={createExpense.error?.message}
            onCancel={() => setCreating(false)}
            onSubmit={(values) =>
              createExpense.mutate(toPayload(values), { onSuccess: () => setCreating(false) })
            }
          />
        )}
      </Modal>

      <Modal
        open={Boolean(editing)}
        onClose={() => setEditing(null)}
        title="Edit expense"
        size="lg"
        align="top"
      >
        {editing && (
          <ExpenseForm
            expense={editing}
            categories={categories}
            isPending={updateExpense.isPending}
            error={updateExpense.error?.message}
            onCancel={() => setEditing(null)}
            onSubmit={(values) =>
              updateExpense.mutate(
                { id: editing.id, ...toPayload(values) },
                { onSuccess: () => setEditing(null) },
              )
            }
          />
        )}
      </Modal>

      <ConfirmDialog
        open={Boolean(deleting)}
        onClose={() => setDeleting(null)}
        title="Delete this expense?"
        body={deleting ? `${deleting.description}, ${money(deleting.amount)}.` : ''}
        confirmLabel="Delete expense"
        loading={deleteExpense.isPending}
        error={deleteExpense.error?.message}
        onConfirm={() =>
          deleteExpense.mutate(deleting.id, { onSuccess: () => setDeleting(null) })
        }
      />
    </>
  );
}

export default AdminExpensesPage;
